server:
  port: 8060

spring:
  application:
    name: db
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:test.db

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: sqlite
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    testdb:
      show-sql:true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka