server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: db
          uri: 'lb://db'
          predicates:
            - Path=/product/**
        - id: ms-sendermail
          uri: 'lb://ms-sendermail'
          predicates:
            - Path=/v1/**
eureka:
  client:
    register-with-eureka: false
